Repository SatelliteQE/nailgun, pull requests merged in 2018-11, with the labels that each got.

#551 Fix Product sync_plan field read
  nailgun/entities.py
Labels: bug, review

#536 Added compliance policies entity
  nailgun/entities.py
Labels: review

#541 Added VirtWhoConfig entity to test the virt-who configure plugin
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#532 Don't require content_view_version_id kwargs to CVV incremental_update()
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#564 Revert "Don't require content_view_version_id kwargs to CVV incremental_update()"
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#544 Revert "Add more attrs to ContentViewVersion"
  nailgun/entities.py
Labels: bug, review

#529 add Foreman Status entity
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
Labels: review

#554 Use content credentials katello API instead of old gpg_keys
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.5, review

#563 Fix VirtWhoConfig.update_payload
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#528 Make repository_sets use /repository_sets/
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#567 CVV have lifecycle environments, not puppet envs
  nailgun/entities.py
Labels: review

#569 lower the chunk size for content uploads to 2MB
  nailgun/entities.py
Labels: review

#562 Add File entity
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#570 Add MTU support to subnets
  nailgun/entities.py
Labels: review
