Repository SatelliteQE/nailgun, pull requests merged in 2018-12, with the labels that each got.

#576 Read Pool ID of Subscription
  nailgun/entities.py
Labels: review

#573 Add registry name fields to Lifecycle Environment
  nailgun/entities.py
Labels: 6.5, review

#574 Send product_id to Enable/disable/available_repositories repository_s…
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#575 Add Support for adding subscriptions to host
  nailgun/entities.py
  tests/test_entities.py
Labels: review

#577 added foreman_tasks_recurring_logic_id in sync plan entity
  nailgun/entities.py
Labels: review

#585 Add File entity
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.4

#592 Added org and loc for authsource entity
  nailgun/entities.py
Labels: review

#586 Add more attrs to ContentViewVersion
  nailgun/entities.py
Labels: 6.4

#588 Use content credentials katello API instead of old gpg_keys (#554)
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.4

#589 add Composite Content View Support (#558)
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.4
