Repository SatelliteQE/nailgun, pull requests merged in 2019-01, with the labels that each got.

#608 [Cherry-pick 6.4.z] Add Job Invocation entity
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.4, review

#610 Made UserGroup entity searchable
  nailgun/entities.py
Labels: 6.5, review

#609 Add Job Invocation entity
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.3, review

#601 Added external usergroup entity
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.5, review
