Repository SatelliteQE/nailgun, pull requests merged in 2020-05, with the labels that each got.

#717 subnet fix mt to mtu [1-liner]
  nailgun/entities.py
Labels: bug

#724 deleting all occurencies of config template
  nailgun/entities.py
  tests/test_entities.py
Labels: review, test-failure

#723 add audit_comments to the ignored fields for ProvisioningTemplate
  nailgun/entities.py
Labels: review
