Repository SatelliteQE/nailgun, pull requests merged in 2020-11, with the labels that each got.

#763 [cherry-pick to stable] traces status ignored
  nailgun/entities.py
Labels: ready

#766 Rename to _updatable_fields and do not return it in get_values
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: bug

#771 [cherry-pick 6.8.z] Rename to _updatable_fields and do not return it in get_values
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: 6.8, bug
