Repository SatelliteQE/nailgun, pull requests merged in 2020-12, with the labels that each got.

#776 Fix whitespace in API path
  nailgun/entities.py
Labels: bug

#772 Adding original_module_streams field to filter
  nailgun/entities.py
Labels: fields

#767 Remove long deprecated entities and Version based logic blocks
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
Labels: Version Cleanup
