Repository SatelliteQE/nailgun, pull requests merged in 2021-01, with the labels that each got.

#779 Added "created_at" and "updated_at" in the settings ignore field.
  nailgun/entities.py
Labels: 6.9, fields, test-failure

#780 Update virt-who entity as http option has been changed
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.9, test-failure

#637 Create the Pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review

#730 add task_id parameter to TaskTimedOutError and TaskFailedError
  nailgun/entity_mixins.py
Labels: enhancement
