Repository SatelliteQE/nailgun, pull requests merged in 2021-11, with the labels that each got.

#791 Add nailgun support for RHCloud Inventory API
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.10

#796 Nailgun Github Action Checks Added
  .codecov.yml
  .coveragerc
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  .travis.yml
  README.rst
  requirements-dev.txt
  setup.py
Labels: enhancement

#795 added support for the registration api command generation
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.10

#797 Add ansible-collection related fields
  nailgun/entities.py
Labels: 6.10

#792 Adding size attribute to ContentUpload
  nailgun/entities.py
Labels: bug, 6.10, Critical
