Repository SatelliteQE/nailgun, pull requests merged in 2022-03, with the labels that each got.

#817 Add token among host fields
  nailgun/entities.py
Labels: fields, 7.0

#819 Add token into the ignore list
  nailgun/entities.py
Labels: 7.0

#820 Condition for token ignore
  nailgun/entities.py
Labels: 7.0

#821 Fix override value
  nailgun/entities.py
Labels: 7.0

#822 Add more OS to list for more coverage
  nailgun/entities.py
Labels: 6.10

#824 Add more OS to list for 6.11
  nailgun/entities.py
Labels: 7.0
