Repository SatelliteQE/nailgun, pull requests merged in 2023-01, with the labels that each got.

#867 Fix unit tests for invalid config
  tests/test_config.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#868 [6.11.z] Fix unit tests for invalid config
  tests/test_config.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#869 [6.12.z] Fix unit tests for invalid config
  tests/test_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#870 [6.13.z] Fix unit tests for invalid config
  tests/test_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#861 [6.13.z] Cherrypicking based on branch labels added to the parent PR
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#863 [6.12.z] Cherrypicking based on branch labels added to the parent PR
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#862 [6.11.z] Cherrypicking based on branch labels added to the parent PR
  .github/workflows/auto_cherry_pick.yml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#871 [6.13.z] Changing inputs as a optional parameter in job-invocation
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#872 [6.12.z] Changing inputs as a optional parameter in job-invocation
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#873 [6.11.z] Changing inputs as a optional parameter in job-invocation
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#874 No Cherrypick by default
  .github/workflows/auto_cherry_pick.yml
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#877 [6.11.z] No Cherrypick by default
  .github/workflows/auto_cherry_pick.yml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#876 [6.13.z] No Cherrypick by default
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#875 [6.12.z] No Cherrypick by default
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#864 fix for ContentView server_config auth values
  nailgun/entities.py
Labels: CherryPick, 6.12.z, 6.13.z

#865 Add new fields to RegistrationCommand entity
  nailgun/entities.py
Labels: CherryPick, 6.12.z, 6.13.z

#879 [6.12.z] fix for ContentView server_config auth values
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#880 [6.13.z] fix for ContentView server_config auth values
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#882 [6.13.z] Add new fields to RegistrationCommand entity
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#883 [6.12.z] Add new fields to RegistrationCommand entity
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#881 Change path to point to proper endpoint
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick

#885 Cherry-pick Ansible Role work to 6.13
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick

#884 Cherrypick Ansible Role work to 6.12.z
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick

#886 Feature changes for GCE plugin
  nailgun/entities.py
Labels: enhancement, CherryPick, 6.13.z
