Repository SatelliteQE/nailgun, pull requests merged in 2023-09, with the labels that each got.

#992 AK update must contain org id, it is a required field
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.14.z

#993 [6.14.z] AK update must contain org id, it is a required field
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#997 Remove pre-commit GH action
  .github/workflows/pull_requests.yml
  .pre-commit-config.yaml
Labels: CherryPick, 6.12.z, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z
