Repository SatelliteQE/nailgun, pull requests merged in 2023-02, with the labels that each got.

#887 [6.13.z] Feature changes for GCE plugin
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#878 added support for auto-merge in nailgun repo
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#888 poll for task intended to fail
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: CherryPick, 6.13.z

#893 [6.13.z] poll for task intended to fail
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#894 Test fix for Networking tests
  nailgun/entities.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#890 [6.12.z] added support for auto-merge in nailgun repo
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#891 [6.11.z] added support for auto-merge in nailgun repo
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#895 [6.12.z] Test fix for Networking tests
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#896 [6.13.z] Test fix for Networking tests
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#897 [6.11.z] Test fix for Networking tests
  nailgun/entities.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked
