Repository SatelliteQE/nailgun, pull requests merged in 2023-06, with the labels that each got.

#924 [6.13.z] Add cacert to .fields in HttpProxy
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, 6.14.z

#927 Add and remove ansible_role to host/hostgroup
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Stream

#929 Add and remove ansible_role to host/hostgroup (#927)
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, 6.14.z

#935 Add helper to delete LCE from capsule
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.13.z, 6.14.z

#937 [6.14.z] Add helper to delete LCE from capsule
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#938 [6.13.z] Add helper to delete LCE from capsule
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#920 Add support for RHCloud Cloud Connector
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.12.z, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z

#939 [6.13.z] Add support for RHCloud Cloud Connector
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#928 Add TablePreferences entity
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
Labels: CherryPick, 6.14.z

#944 [6.14.z] Add TablePreferences entity
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#933 [6.14.z] fixed the cherry pick GHA
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#945 [6.14.z] Nailgun Updates for Needs_publish feature
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z
