Repository SatelliteQE/nailgun, pull requests merged in 2023-11, with the labels that each got.

#1029 fixed the type error for some remaining entities
  nailgun/entities.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#1031 [6.14.z] fixed the type error for some remaining entities
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1033 Changes for 6.15.z new branch
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick, 6.15.z

#1036 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1035 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1034 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z
