Repository SatelliteQE/nailgun, pull requests merged in 2023-03, with the labels that each got.

#898 Add support for reading a Provisioning Template
  nailgun/entities.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#903 [6.12.z]Add read template support 6.12.z
  nailgun/entities.py
Labels: No-CherryPick, 6.12.z

#904 [6.11.z]Add read template support 6.11.z
  nailgun/entities.py
Labels: 6.11.z, No-CherryPick

#889 ahv_internal_debug option support for virt-who configuration
  nailgun/entities.py
Labels: CherryPick, Auto_Cherry_Picked, 6.13.z

#905 [6.13.z] ahv_internal_debug option support for virt-who configuration
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z
