Repository SatelliteQE/nailgun, pull requests merged in 2023-07, with the labels that each got.

#936 Play ansible roles on host
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#954 Adding entity mixins classes
  nailgun/entities.py
Labels: CherryPick, 6.12.z

#950 [6.14.z] remove g-chat notification for failed auto cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#957 [6.12.z] - remove g-chat notification for failed auto-cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#956 [6.13.z] - remove g-chat notification for failed auto-cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#955 [6.12.z] Adding entity mixins classes
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#958 [6.11.z] - remove g-chat notification for failed auto-cherrypick, handled in slack
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick

#948 [6.14.z] Play ansible roles on host
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#959 [6.13] Play ansible roles on host
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick

#960 [6.12] Play ansible roles on host
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick

#962 [6.14.z] Trigger robottelo image update workflow on merge
  .github/workflows/trigger_robottelo_workflow.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#963 [6.11.z] Trigger robottelo image update workflow on merge
  .github/workflows/trigger_robottelo_workflow.yml
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#965 [6.12.z] Trigger robottelo image update workflow on merge
  .github/workflows/trigger_robottelo_workflow.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#964 [6.13.z] Trigger robottelo image update workflow on merge
  .github/workflows/trigger_robottelo_workflow.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#966 Add pxe_loader to Host
  nailgun/entities.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#973 [6.14.z] Remove Python 3.9 support from nailgun
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#975 [6.13.z] Remove Python 3.9 support from nailgun
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#972 [6.12.z] Remove Python 3.9 support from nailgun
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#974 [6.11.z] Remove Python 3.9 support from nailgun
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#971 [6.11.z] Add pxe_loader to Host
  nailgun/entities.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#968 [6.14.z] Add pxe_loader to Host
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#969 [6.13.z] Add pxe_loader to Host
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z
