Repository SatelliteQE/nailgun, pull requests merged in 2023-08, with the labels that each got.

#978 Changing return value for Discovery create method
  nailgun/entities.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#979 [6.12.z] Changing return value for Discovery create method
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#980 [6.14.z] Changing return value for Discovery create method
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#981 [6.13.z] Changing return value for Discovery create method
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#977 Introduce new project code standards
  .coveragerc
  .flake8
  .gitignore
  .pre-commit-config.yaml
  docs/conf.py
  docs/create_user_nailgun.py
  docs/create_user_plain.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  requirements-dev.txt
  setup.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z, 6.14.z

#983 [6.14.z] Introduce new project code standards
  .coveragerc
  .flake8
  .gitignore
  .pre-commit-config.yaml
  docs/conf.py
  docs/create_user_nailgun.py
  docs/create_user_plain.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  requirements-dev.txt
  setup.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#988 [6.12.z] Introduce new project code standards (#977)
  .coveragerc
  .flake8
  .gitignore
  .pre-commit-config.yaml
  docs/conf.py
  docs/create_user_nailgun.py
  docs/create_user_plain.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  requirements-dev.txt
  setup.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, 6.12.z

#987 [6.13.z] Introduce new project code standards (#977)
  .coveragerc
  .flake8
  .gitignore
  .pre-commit-config.yaml
  docs/conf.py
  docs/create_user_nailgun.py
  docs/create_user_plain.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  requirements-dev.txt
  setup.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, 6.13.z
