Repository SatelliteQE/nailgun, pull requests merged in 2023-10, with the labels that each got.

#994 Introduce docstring standards for Ruff
  docs/create_user_plain.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#1009 [6.14.z] Introduce docstring standards for Ruff
  docs/create_user_plain.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked

#1010 [6.13.z] Introduce docstring standards for Ruff
  docs/create_user_plain.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  pyproject.toml
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, 6.13.z

#1013 Add catalog info for backstage
  catalog-info.yaml
Labels: No-CherryPick

#999 [6.14.z] Remove pre-commit GH action
  .github/workflows/pull_requests.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#998 [6.13.z] Remove pre-commit GH action
  .github/workflows/pull_requests.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1000 [6.12.z] Remove pre-commit GH action
  .github/workflows/pull_requests.yml
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, AutoMerge_Cherry_Picked

#1015 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1016 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#995 Removing auto release WF from non-master branches
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick, 6.14.z

#1017 Add support for capsule content counts
  nailgun/entities.py
  tests/test_entities.py
Labels: enhancement, No-CherryPick, Stream

#1012 Remove katello-agent related entities
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Stream

#1019 Add missing counts provided by CVV endpoint
  nailgun/entities.py
Labels: fields, CherryPick, 6.14.z

#1020 [6.14.z] Add missing counts provided by CVV endpoint
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#996 fixing the memory issue in auto-cherry-pick GHA
  .github/workflows/auto_cherry_pick.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#1023 [6.14.z] fixing the memory issue in auto-cherry-pick GHA
  .github/workflows/auto_cherry_pick.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1024 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1025 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1026 [6.12.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z
