Repository SatelliteQE/nailgun, pull requests merged in 2023-05, with the labels that each got.

#914 Upgrade codecov dependency
  requirements-dev.txt
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#907 [6.12.z] Ignore puppetclass attribute conditionally
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#908 [6.13.z] Ignore puppetclass attribute conditionally
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#909 [6.11.z] Ignore puppetclass attribute conditionally
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked

#921 Add filters_applied field
  nailgun/entities.py
Labels: No-CherryPick

#915 Auto Release Nailgun
  .github/workflows/dispatch_release.yml
Labels: Framework Changes, No-CherryPick

#925 AutoCherrypick of Merged PRs
  .github/workflows/auto_cherry_pick.yml
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#926 [6.12.z] poll for task intended to fail
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: No-CherryPick, 6.12.z

#918 [6.13.z] Upgrade codecov dependency
  requirements-dev.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#919 [6.12.z] Upgrade codecov dependency
  requirements-dev.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#917 [6.11.z] Upgrade codecov dependency
  requirements-dev.txt
Labels: 6.11.z, No-CherryPick, Auto_Cherry_Picked
