Repository SatelliteQE/nailgun, pull requests merged in 2023-04, with the labels that each got.

#906 Ignore puppetclass attribute conditionally
  nailgun/entities.py
  tests/test_entities.py
Labels: 6.11.z, CherryPick, 6.12.z, 6.13.z

#911 Add AlternateContentSource entity
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.13.z

#910 host: add support for reading provisioning templates
  nailgun/entities.py
Labels: CherryPick, 6.13.z

#912 [6.13.z] Add AlternateContentSource entity
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z
