Repository SatelliteQE/nailgun, pull requests merged in 2024-08, with the labels that each got.

#1203 Add support for debian repository creation
  nailgun/entities.py
Labels: CherryPick, 6.15.z

#1208 [6.15.z] host: added field reported_data
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1211 [6.15.z] Add support for debian repository creation
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1215 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  docs/conf.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1214 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  docs/conf.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1213 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  docs/conf.py
  nailgun/__init__.py
  nailgun/client.py
  nailgun/config.py
  nailgun/entities.py
  nailgun/entity_fields.py
  nailgun/entity_mixins.py
  tests/test_client.py
  tests/test_config.py
  tests/test_entities.py
  tests/test_entity_fields.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1218 [6.16.z]: Changes for 6.16.z new branch
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick
