Repository SatelliteQE/nailgun, pull requests merged in 2024-11, with the labels that each got.

#1225 Fix for registration command packages
  nailgun/entities.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z, 6.16.z

#1243 [6.16.z] Fix for registration command packages
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1245 [6.15.z] Fix for registration command packages
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1244 [6.14.z] Fix for registration command packages
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1250 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, 6.14.z

#1210 Add repo_data option to host registration command
  nailgun/entities.py
Labels: CherryPick, 6.16.z

#1256 [6.16.z] Add repo_data option to host registration command
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1258 Remove Purpose addons from Nailgun
  nailgun/entities.py
Labels: No-CherryPick, Stream
