Repository SatelliteQE/nailgun, pull requests merged in 2024-04, with the labels that each got.

#1118 new entity NotificationRecipients
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z, PRT-Passed

#1113 addition of auto-branching process as part of github action
  .github/workflows/auto_branching.yml
Labels: No-CherryPick

#1125 [6.15.z] new entity NotificationRecipients
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1114 [6.15.z] adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1117 [6.14.z] adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1116 [6.13.z] adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1115 [6.12.z] adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1110 [6.12.z] update entity object with parametrized server_config rather default
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1124 [6.14.z] new entity NotificationRecipients
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1126 [6.15.z] Remove codecov
  .codecov.yml
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  Makefile
  pyproject.toml
  requirements-dev.txt
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z

#1131 [6.13.z]Remove codecov
  .codecov.yml
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  Makefile
  pyproject.toml
  requirements-dev.txt
Labels: No-CherryPick, 6.13.z

#1132 [6.12.z] Remove codecov
  .codecov.yml
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  Makefile
  pyproject.toml
  requirements-dev.txt
Labels: No-CherryPick, 6.12.z

#1119 Add json response to entity creation error message
  nailgun/entity_mixins.py
  tests/test_entity_mixins.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z, PRT-Passed
