Repository SatelliteQE/nailgun, pull requests merged in 2024-10, with the labels that each got.

#1227 [6.15.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1228 [6.14.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1230 [6.16.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4
  .github/workflows/automerge.yaml
Labels: No-CherryPick, 6.16.z

#1229 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1224 Abstract adding json respone to error message
  nailgun/entity_mixins.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#1234 [6.14.z] Abstract adding json respone to error message
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1235 [6.16.z] Abstract adding json respone to error message
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1236 [6.15.z] Abstract adding json respone to error message
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1233 Add possibility to query deb packages for host
  nailgun/entities.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#1238 [6.16.z] Add possibility to query deb packages for host
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1237 [6.15.z] Add possibility to query deb packages for host
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1239 [6.14.z] Add possibility to query deb packages for host
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z
