Repository SatelliteQE/nailgun, pull requests merged in 2024-06, with the labels that each got.

#1189 [master]: Changes for 6.16.z new branch
  .github/dependabot.yml
Labels: No-CherryPick

#1191 Add support for OS Parameters
  nailgun/entities.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1194 [6.15.z] Add support for OS Parameters
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1193 [6.14.z] Add support for OS Parameters
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1192 [6.13.z] Add support for OS Parameters
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1195 PR checks for python 3.12
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1200 PR checks for python 3.12 (#1195)
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
Labels: No-CherryPick, 6.14.z

#1201 PR checks for python 3.12 (#1195)
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
Labels: No-CherryPick, 6.13.z
