Repository SatelliteQE/nailgun, pull requests merged in 2024-07, with the labels that each got.

#1204 Add password field for CR image creation
  nailgun/entities.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1207 [6.15.z] Add password field for CR image creation
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1205 [6.14.z] Add password field for CR image creation
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1206 [6.13.z] Add password field for CR image creation
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked

#1202 host: added field reported_data
  nailgun/entities.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed
