Repository SatelliteQE/nailgun, pull requests merged in 2024-03, with the labels that each got.

#1106 update entity object with parametrized server_config rather default
  nailgun/entity_mixins.py
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z

#1107 [6.15.z] update entity object with parametrized server_config rather default
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1108 [6.13.z] update entity object with parametrized server_config rather default
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1109 [6.14.z] update entity object with parametrized server_config rather default
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1111 Add support for the reclaim_space endpoint
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.15.z

#1102 Remove codecov
  .codecov.yml
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  Makefile
  pyproject.toml
  requirements-dev.txt
Labels: No-CherryPick

#1089 adding the PRT result and labels on github comment
  .github/workflows/prt_labels.yml
  .github/workflows/prt_result.yml
Labels: CherryPick, 6.12.z, 6.13.z, 6.14.z, 6.15.z
