Repository SatelliteQE/nailgun, pull requests merged in 2024-05, with the labels that each got.

#1137 [6.15.z] Add json response to entity creation error message
  nailgun/entity_mixins.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z, PRT-Failed

#1139 Add outputs, rerun, cancel endpoints in JobInvocation entity
  nailgun/entities.py
Labels: CherryPick, 6.13.z, AutoMerge_Cherry_Picked, 6.14.z, 6.15.z

#1138 Add new verify_checksum endpoints
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick

#1140 [6.15.z] Add outputs, rerun, cancel endpoints in JobInvocation entity
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z, PRT-Passed

#1141 [6.13.z] Add outputs, rerun, cancel endpoints in JobInvocation entity
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked, PRT-Passed

#1142 [6.14.z] Add outputs, rerun, cancel endpoints in JobInvocation entity
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1143 Use type(self) instead of entity class name in create methods
  nailgun/entities.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1149 [6.14.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1148 [6.13.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1147 [6.12.z] Bump kentaro-m/auto-assign-action from 1.2.6 to 2.0.0
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1152 Use server_config as named argument only
  docs/create_organization_nailgun.py
  docs/create_user_nailgun.py
  docs/index.rst
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
  tests/test_entity_mixins.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1153 Update Entity.__eq__ isinstance check to work in either direction
  nailgun/entity_mixins.py
Labels: CherryPick, 6.13.z, 6.14.z, 6.15.z

#1146 [6.14.z] Use type(self) instead of entity class name in create methods
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1144 [6.15.z] Use type(self) instead of entity class name in create methods
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1157 [6.13.z] Update Entity.__eq__ isinstance check to work in either direction
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1158 [6.14.z] Update Entity.__eq__ isinstance check to work in either direction
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1159 [6.15.z] Update Entity.__eq__ isinstance check to work in either direction
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1163 [6.14.z] Use server_config as named argument only
  docs/create_organization_nailgun.py
  docs/create_user_nailgun.py
  docs/index.rst
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1161 [6.15.z] Use server_config as named argument only
  docs/create_organization_nailgun.py
  docs/create_user_nailgun.py
  docs/index.rst
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1165 [6.13.z] Fix entity create methods
  docs/create_organization_nailgun.py
  docs/create_user_nailgun.py
  docs/index.rst
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, PRT-Passed

#1185 [6.15.z] - Handle failed workflow cherry-picks
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick, 6.15.z, dependencies

#1186 [6.14.z] - Handle failed workflow cherry-picks
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick, 6.14.z, dependencies

#1187 [6.13.z] - Handle failed workflow cherry-picks
  .github/workflows/auto_cherry_pick.yml
  .github/workflows/automerge.yaml
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick, 6.13.z, dependencies

#1135 [6.14.z] Add json response to entity creation error message
  nailgun/entity_mixins.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z, PRT-Passed

#1134 [6.13.z] Add json response to entity creation error message
  nailgun/entity_mixins.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z, AutoMerge_Cherry_Picked, PRT-Passed

#1136 [6.12.z] Add json response to entity creation error message
  nailgun/entity_mixins.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z, PRT-Failed
