Repository SatelliteQE/nailgun, pull requests merged in 2024-01, with the labels that each got.

#1050 Add Dependabot Configuration YAML
  .github/dependabot.yml
Labels: No-CherryPick

#1057 [6.15.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1058 [6.13.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1059 [6.14.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1076 [6.14.z] Bump actions/stale from 6 to 9
  .github/workflows/stale.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1073 [6.15.z] Bump actions/stale from 6 to 9
  .github/workflows/stale.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1075 [6.13.z] Bump actions/stale from 6 to 9
  .github/workflows/stale.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.13.z

#1074 [6.12.z] Bump actions/stale from 6 to 9
  .github/workflows/stale.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1066 [6.13.z] Bump pre-commit/action from 2.0.0 to 3.0.0
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick, 6.13.z

#1065 [6.12.z] Bump pre-commit/action from 2.0.0 to 3.0.0
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1064 [6.14.z] Bump pre-commit/action from 2.0.0 to 3.0.0
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1062 [6.12.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.12.z

#1063 [6.14.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1060 [6.15.z] Bump kentaro-m/auto-assign-action from 1.2.4 to 1.2.6
  .github/workflows/auto_assignment.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z
