Repository SatelliteQE/nailgun, pull requests merged in 2025-08, with the labels that each got.

#1324 Add description key to _fields dictionary
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z

#1326 [6.17.z] Add description key to _fields dictionary
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#1318 [6.17.z] Replace hardcoded temp file path with tempfile in tests/test_config.py
  tests/test_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1320 [6.16.z] Replace hardcoded temp file path with tempfile in tests/test_config.py
  tests/test_config.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1329 [6.15.z] Fix ruff linting issues to prepare for version bump
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1331 [6.16.z] Fix ruff linting issues to prepare for version bump
  nailgun/entities.py
  nailgun/entity_mixins.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1333 [6.17.z] [pre-commit.ci] pre-commit autoupdate
  .pre-commit-config.yaml
  tests/test_config.py
  tests/test_entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1337 Add application_name field to FlatpakRemoteRepository
  nailgun/entities.py
Labels: No-CherryPick, Stream

#1343 [6.15.z] Bump lewagon/wait-on-check-action from 1.3.4 to 1.4.0
  .github/workflows/automerge.yaml
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z
