Repository SatelliteQE/nailgun, pull requests merged in 2025-02, with the labels that each got.

#1220 Add AnsibleVariable to entities
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z

#1266 [6.16.z] Add AnsibleVariable to entities
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1267 [6.14.z] Add AnsibleVariable to entities
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1257 Enable download utility selection
  nailgun/entities.py
Labels: No-CherryPick

#1262 [6.16.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1269 [6.14.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
Labels: No-CherryPick, 6.14.z

#1268 [6.15.z] Add Python 3.13 for PR checks in GHA
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
Labels: No-CherryPick, 6.15.z

#1270 Using Py3.13 for build/publish to PyPI GHA
  .github/workflows/merge_to_master.yml
Labels: No-CherryPick

#1273 [6.16.z] Update Hostgroup and host class with subnet6 for IPv6
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1274 [6.15.z] Update Hostgroup and host class with subnet6 for IPv6
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.15.z

#1275 [6.14.z] Update Hostgroup and host class with subnet6 for IPv6
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.14.z

#1260 Add support for Registration Tokens
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Stream

#1254 Add boolean field for content_default_http_proxy in HTTProxy entity
  nailgun/entities.py
Labels: No-CherryPick

#1276 Add RHCloud.advisor_engine_config API
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Stream

#1278 Auto branching: Add randomness to branch name
  .github/workflows/auto_branching.yml
Labels: No-CherryPick

#1279 [master]: Changes for 6.17.z new branch
  .github/dependabot.yml
Labels: No-CherryPick

#1280 [6.17.z]: Changes for 6.17.z new branch
  .github/dependabot.yml
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick

#1272 Add donwload cuncurrency for repository
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.16.z

#1281 [6.16.z] Add donwload cuncurrency for repository
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1282 Add ip6 for host class
  nailgun/entities.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.17.z

#1283 [6.17.z] Add ip6 for host class
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.17.z

#1277 Add view/entity for booted container images page
  nailgun/entities.py
Labels: CherryPick, 6.17.z
