Repository SatelliteQE/nailgun, pull requests merged in 2025-03, with the labels that each got.

#1286 Add setuptools to dev dependencies
  requirements-dev.txt
Labels: CherryPick, 6.14.z, 6.15.z, dependencies, maintenance, 6.16.z, 6.17.z

#1288 [6.17.z] Add setuptools to dev dependencies
  requirements-dev.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1287 [6.16.z] Add setuptools to dev dependencies
  requirements-dev.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1290 [6.15.z] Add setuptools to dev dependencies
  requirements-dev.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.15.z

#1289 [6.14.z] Add setuptools to dev dependencies
  requirements-dev.txt
Labels: No-CherryPick, Auto_Cherry_Picked, 6.14.z

#1285 Remove Python 3.10 support
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: CherryPick, 6.14.z, 6.15.z, 6.16.z, 6.17.z

#1291 [6.16.z] Remove Python 3.10 support
  .github/workflows/merge_to_master.yml
  .github/workflows/pull_requests.yml
  setup.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.16.z

#1284 [6.17.z] Add view/entity for booted container images page
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z
