Repository SatelliteQE/nailgun, pull requests merged in 2025-06, with the labels that each got.

#1304 ContentView::RemoveVersion (from the CV and any ENVs)
  nailgun/entities.py
Labels: CherryPick, Stream, 6.16.z, 6.17.z

#1306 Add JobTemplate.clone API
  nailgun/entities.py
Labels: No-CherryPick

#1309 [6.17.z] ContentView::RemoveVersion (from the CV and any ENVs)
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1311 Add explicit timeout to `entity_callable()` invocation in `call_entity_with_timeout()`
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: CherryPick, 6.15.z, 6.16.z, 6.17.z

#1312 [6.17.z] Add explicit timeout to `entity_callable()` invocation in `call_entity_with_timeout()`
  nailgun/entities.py
  nailgun/entity_mixins.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1314 Add http_proxy to the SmartProxy entity
  nailgun/entities.py
  tests/test_entities.py
Labels: CherryPick, 6.17.z

#1315 [6.17.z] Add http_proxy to the SmartProxy entity
  nailgun/entities.py
  tests/test_entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z
