Repository SatelliteQE/nailgun, pull requests merged in 2025-09, with the labels that each got.

#1346 [master]: Changes for 6.18.z new branch
  .github/dependabot.yml
Labels: No-CherryPick

#1347 [6.18.z]: Changes for 6.18.z new branch
  .github/dependabot.yml
  .github/workflows/auto_branching.yml
  .github/workflows/dispatch_release.yml
Labels: No-CherryPick

#1349 Add Export function to ReportTemplate class
  nailgun/entities.py
Labels: CherryPick, AutoMerge_Cherry_Picked, 6.15.z, 6.16.z, 6.17.z, 6.18.z

#1357 Add entity for content view environments endpoint
  nailgun/entities.py
Labels: CherryPick, 6.16.z, 6.17.z, 6.18.z

#1352 [6.16.z] Add Export function to ReportTemplate class
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, AutoMerge_Cherry_Picked, 6.16.z

#1355 [6.17.z] Add Export function to ReportTemplate class
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.17.z

#1360 [6.18.z] Add entity for content view environments endpoint
  nailgun/entities.py
Labels: No-CherryPick, Auto_Cherry_Picked, 6.18.z
